spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/algosipeosseong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: daijin

  data:
    redis:
      host: localhost
      port: 6379
      password: daijin

logging:
  level:
    org:
      springframework:
        security:
          DEBUG